import type { Incident, Section } from '~/types'

export const SECTIONS: Section[] = [
  {
    key: 'tempi',
    label: 'Τέμπη',
    description: 'Η σύγκρουση τρένων (28/2/2023, 57 νεκροί) και η συγκάλυψη πολιτικών ευθυνών.',
    icon: '🚆'
  },
  {
    key: 'ypoklopες',
    label: 'Υποκλοπές / Predator',
    description: 'Παράνομη παρακολούθηση με Predator και ΕΥΠ. Εμπλοκή κρατικών οργάνων στη συγκάλυψη.',
    icon: '📡'
  },
  {
    key: 'opekepe',
    label: 'ΟΠΕΚΕΠΕ',
    description: 'Απάτη αγροτικών επιδοτήσεων. Πρόστιμο ΕΕ €415 εκατ. Αυτοκτονίες κτηνοτρόφων.',
    icon: '🌾'
  },
  {
    key: 'typos',
    label: 'Ελευθερία Τύπου',
    description: 'Τελευταία χώρα της ΕΕ σε ελευθερία Τύπου. Επιχειρήσεις διαδικτυακής επιρροής.',
    icon: '📰'
  },
  {
    key: 'thesmoi',
    label: 'Θεσμοί',
    description: 'Συγκρούσεις δικαστικής, εκτελεστικής και νομοθετικής εξουσίας.',
    icon: '⚖️'
  },
]

export const INCIDENTS: Incident[] = [
  // ── ΤΕΜΠΗ ──────────────────────────────────────────────────────────────────
  {
    id: 'tempi-1',
    title: 'Κατάρρευση Σιδηροδρομικού Δικτύου',
    date: 'Μάρτιος 2023 – Σήμερα',
    category: 'Β\'',
    type: 'Αδυναμία Κράτους',
    description: 'Μετά το δυστύχημα, μεγάλο μέρος του δικτύου υπολειτουργεί ή εκτελείται με λεωφορεία αντικατάστασης. Αδυναμία αποκατάστασης κρίσιμης δημόσιας υποδομής τρία χρόνια μετά.',
    documentation_order: 'Α\'',
    references: [],
    score: 7,
    status: 'Ενεργό',
    section: 'tempi',
  },
  {
    id: 'tempi-2',
    title: 'Δήλωση Kövesi για Άρθρο 86',
    date: '2 Οκτωβρίου 2025',
    category: 'Α\'',
    type: 'Θεσμική',
    description: 'Η Ευρωπαία Εισαγγελέας Laura Kövesi δήλωσε δημόσια ότι το Άρθρο 86 του Συντάγματος εμπόδισε την EPPO να ολοκληρώσει τις έρευνές της στις υποθέσεις ΟΠΕΚΕΠΕ και Τεμπών, και κάλεσε σε αναθεώρησή του. Χωρίς άρση ασυλίας από τη Βουλή, αδύνατη η δίωξη πρώην υπουργών για τη Σύμβαση 717.',
    documentation_order: 'Β\'',
    references: [
      'https://www.naftemporiki.gr/politics/2014073/kovesi-i-anatheorisi-toy-arthroy-86-parempodise-tin-ereyna-mas-statempi-kai-ton-opekepe/',
      'https://www.documentonews.gr/article/kovesi-allaxte-to-arthro-86-gia-na-diokoumepolitikoys/',
    ],
    score: 9,
    status: 'Ενεργό',
    section: 'tempi',
  },
  {
    id: 'tempi-3',
    title: 'Έγγραφο-Ντοκουμέντο για το Μπάζωμα',
    date: '7 Φεβρουαρίου 2025',
    category: 'Β\'',
    type: 'Θεσμική Συγκάλυψη',
    description: 'Επίσημο έγγραφο Εισαγγελίας Εφετών Λάρισας βεβαιώνει ότι το μπάζωμα στα Τέμπη έγινε χωρίς εισαγγελική παραγγελία. Η Εισαγγελία δεν προχώρησε αυτεπάγγελτα σε έρευνα για τον εκδότη της εντολής.',
    documentation_order: 'Α\'',
    references: [
      'https://www.documentonews.gr/article/eisaggelia-efeton-larisas-to-mpazoma-sta-tempi-egine-xoris-eisaggelikiparaggelia-eggrafo/',
    ],
    score: 10,
    status: 'Ενεργό',
    section: 'tempi',
  },

  // ── ΥΠΟΚΛΟΠΕΣ ──────────────────────────────────────────────────────────────
  {
    id: 'predator-1',
    title: 'Σύγκρουση ΑΔΑΕ – Εισαγγελίας Αρείου Πάγου',
    date: '10 Ιανουαρίου 2023',
    category: 'Α\'',
    type: 'Θεσμική',
    description: 'Ο Εισαγγελέας Ντογιάκος εξέδωσε γνωμοδότηση (1/2023) απαγορεύοντας ουσιαστικά στην ΑΔΑΕ να ελέγχει παρόχους κινητής για τις υποκλοπές, με απειλή ποινικών κυρώσεων στα μέλη της Αρχής.',
    documentation_order: 'Α\'',
    references: [],
    score: 9,
    status: 'Ενεργό',
    section: 'ypoklopες',
  },
  {
    id: 'predator-2',
    title: 'Δηλώσεις Υπουργών για Υποκλοπές',
    date: '2023',
    category: 'Α\'',
    type: 'Θεσμική',
    description: 'Υπουργοί δήλωσαν δημόσια ότι οι υποκλοπές είναι «ανούσιο θέμα» και ότι «αν δεν σε παρακολουθούν ως υπουργό, δεν κάνεις για τη δουλειά». De facto παραίτηση από το Άρθρο 19 του Συντάγματος (απόρρητο επικοινωνιών).',
    documentation_order: 'Β\'',
    references: [
      'https://www.news247.gr/gnomes/exeftelismos-tous-parakolouthoun-kai-tous-einai-adiaforo/',
    ],
    score: 8,
    status: 'Ενεργό',
    section: 'ypoklopες',
  },
  {
    id: 'predator-3',
    title: 'Στοχοποίηση Χρήστου Ράμμου (Πρόεδρος ΑΔΑΕ)',
    date: '2023–2024',
    category: 'Β\'',
    type: 'Κατασταλτική',
    description: 'Κυβερνητικά στελέχη αποκάλεσαν τον Πρόεδρο της ΑΔΑΕ «ντελιβερά» και «κομματικό όργανο» λόγω των ελέγχων για τις υποκλοπές. Τυπικό παράδειγμα δημόσιας στοχοποίησης ανεξάρτητης αρχής.',
    documentation_order: 'Β\'',
    references: [],
    score: 7,
    status: 'Έκλεισε',
    section: 'ypoklopες',
  },
  {
    id: 'predator-4',
    title: 'Απόφαση ΣτΕ – Ενημέρωση Ανδρουλάκη',
    date: '5 Απριλίου 2024',
    category: 'Ε\'',
    type: 'Σύγκρουση Εξουσιών',
    description: 'Το ΣτΕ έκρινε αντισυνταγματικό τον νόμο απαγόρευσης ενημέρωσης παρακολουθούμενων. Η εφαρμογή δυσχεράνθηκε πρακτικά από μεταβολή σύνθεσης της ΑΔΑΕ.',
    documentation_order: 'Α\'',
    references: [],
    score: 9,
    status: 'Εκκρεμεί',
    section: 'ypoklopες',
  },
  {
    id: 'predator-5',
    title: 'Λίστα Μενουδάκου – 155 Στόχοι Predator',
    date: '2023',
    category: 'Α\'',
    type: 'Θεσμική',
    description: 'Η «λίστα Μενουδάκου» αποκαλύπτει 155 στόχους παρακολούθησης μέσω Predator, ανάμεσά τους βουλευτές, υπουργοί, δημοσιογράφοι και επιχειρηματίες. Περιλαμβάνονται: ΒΟΥΛΗ ΤΩΝ ΕΛΛΗΝΩΝ, ΥΠΟΥΡΓΕΙΟ ΕΘΝΙΚΗΣ ΑΜΥΝΑΣ, ΥΠΟΥΡΓΕΙΟ ΠΡΟΣΤΑΣΙΑΣ ΤΟΥ ΠΟΛΙΤΗ, ΠΡΟΕΔΡΙΑ ΤΗΣ ΚΥΒΕΡΝΗΣΗΣ (×2). Αξιοσημείωτο: ο Πρωθυπουργός απουσιάζει ενώ παρακολουθούνταν υπουργοί του ιδίου κυβερνητικού σχηματισμού.',
    documentation_order: 'Α\'',
    references: [
      'https://www.imerodromos.gr/skandalo-ypoklopon-i-lista-me-toys-155-ypo-parakoloythisi-ypoyrgoi-voyleytesepicheirimaties-dimosiografoi/',
    ],
    score: 9,
    status: 'Ενεργό',
    section: 'ypoklopες',
  },
  {
    id: 'predator-6',
    title: 'Πολιτική Πειθάρχηση Μελών Κυβέρνησης',
    date: 'Μάρτιος 2026',
    category: 'Α\'',
    type: 'Θεσμική',
    description: 'Καταγγελίες για ρητή γραμμή του Μεγάρου Μαξίμου ότι τυχόν κατάθεση μήνυσης από παρακολουθούμενο υπουργό αποτελεί «αφορμή πολέμου» και οδηγεί σε αποπομπή από την κυβέρνηση. De facto παραίτηση των θυμάτων από το δικαίωμα δικαστικής προστασίας με αντάλλαγμα τη διατήρηση του αξιώματος.',
    documentation_order: 'Β\'',
    references: [
      'https://www.dnews.gr/eidhseis/paixnidia-eksousias/578337/ektos-kyvernisis-opoios-ypourgos-katathesei-minysigia-tis-ypoklopes',
    ],
    score: 9,
    status: 'Ενεργό',
    section: 'ypoklopες',
  },

  // ── ΟΠΕΚΕΠΕ ────────────────────────────────────────────────────────────────
  {
    id: 'opekepe-1',
    title: 'Αυτοκτονίες Κτηνοτρόφων',
    date: '2025–2026',
    category: 'Ε\'',
    type: 'Οικονομική',
    description: 'Αυτοκτονίες κτηνοτρόφων ως άμεσο αποτέλεσμα οικονομικής ασφυξίας. Η EPPO έχει αναγνωρίσει σύνδεση με τις παράνομες πρακτικές του οργανισμού που στέρησαν επιδοτήσεις από νόμιμους δικαιούχους.',
    documentation_order: 'Β\'',
    references: [],
    score: 7,
    status: 'Ενεργό',
    section: 'opekepe',
  },
  {
    id: 'opekepe-2',
    title: 'Χρήση Αστυνομίας κατά Αγροτών',
    date: 'Αρχές Ιανουαρίου 2026',
    category: 'Β\'',
    type: 'Κατασταλτική',
    description: 'Το Υπουργείο Προστασίας του Πολίτη έστειλε διμοιρίες εναντίον αγροτών που διαμαρτύρονταν για τον ΟΠΕΚΕΠΕ. Καταγράφηκε σε βίντεο χρήση γκλοπ σε ευαίσθητα σημεία του σώματος.',
    documentation_order: 'Γ\'',
    references: [],
    score: 7,
    status: 'Εκκρεμεί',
    section: 'opekepe',
  },

  // ── ΤΥΠΟΣ ──────────────────────────────────────────────────────────────────
  {
    id: 'typos-1',
    title: 'Κατάταξη RSF',
    date: 'Μάιος 2023, 2024 & 2025',
    category: 'Γ\'',
    type: 'Κοινωνική',
    description: 'Η Ελλάδα κατατάχθηκε τελευταία στην ΕΕ σε ελευθερία Τύπου. 107η παγκοσμίως το 2023, 88η το 2024 και 89η το 2025.',
    documentation_order: 'Α\'',
    references: ['https://rsf.org/en/country/greece'],
    score: 8,
    status: 'Ενεργό',
    section: 'typos',
  },
  {
    id: 'typos-2',
    title: 'Δημοσίευμα Haaretz – «Bots» στις Εκλογές 2023',
    date: '7 Ιανουαρίου 2026',
    category: 'Γ\'',
    type: 'Εκλογική',
    description: 'Δημοσίευμα της Haaretz αποκαλύπτει ότι ισραηλινή εταιρεία πολιτικής επικοινωνίας πραγματοποίησε επιχειρήσεις διαδικτυακής επιρροής (online influence operations) για λογαριασμό της ΝΔ κατά τις εκλογές του 2023.',
    documentation_order: 'Β\'',
    references: [
      'https://www.haaretz.com/israel-news/2026-01-07/ty-article/.premium/israeli-president-herzog-bagged-right-winggreek-election-campaign-job-for-confidant/0000019b-940e-dd67-a9ff-9e0fa16d0000',
    ],
    score: 8,
    status: 'Εκκρεμεί',
    section: 'typos',
  },
  {
    id: 'typos-3',
    title: 'Ψήφισμα Ευρωπαϊκού Κοινοβουλίου',
    date: '7 Φεβρουαρίου 2024',
    category: 'Δ\'',
    type: 'Διεθνής',
    description: 'Το Ευρωπαϊκό Κοινοβούλιο εξέφρασε «σοβαρές ανησυχίες» για το κράτος δικαίου στην Ελλάδα, επικαλούμενο προβλήματα ελευθερίας τύπου, ασφάλειας δημοσιογράφων και ανεξαρτησίας ΜΜΕ.',
    documentation_order: 'Α\'',
    references: [],
    score: 8,
    status: 'Ενεργό',
    section: 'typos',
  },

  // ── ΘΕΣΜΟΙ ─────────────────────────────────────────────────────────────────
  {
    id: 'thesmoi-1',
    title: 'Σύγκρουση EPPO – Αρείου Πάγου',
    date: '14 Νοεμβρίου 2025',
    category: 'Ε\'',
    type: 'Σύγκρουση Εξουσιών',
    description: 'Το Κολλέγιο της EPPO ανανέωσε τη θητεία τριών Εισαγγελέων (υποθέσεις Τεμπών/ΟΠΕΚΕΠΕ) παρά την ενεργή αντίθεση της ηγεσίας του Αρείου Πάγου.',
    documentation_order: 'Α\'',
    references: [],
    score: 9,
    status: 'Ενεργό',
    section: 'thesmoi',
    subsection: 'Δικαστική Εξουσία',
  },
  {
    id: 'thesmoi-2',
    title: 'Κατάρρευση Δικαστικής Έδρας – Δίκη Τεμπών',
    date: '10 Μαρτίου 2026 – Σήμερα',
    category: 'Ε\'',
    type: 'Θεσμική',
    description: 'Σωματική κατάρρευση και κλάμα της Προέδρου επί της έδρας υπό πιέσεις. Ακολούθησε μαζική «ασθένεια» Προέδρου, Εισαγγελέως και Προϊσταμένης Πρωτοδικείου για αποφυγή χορήγησης αντιγράφων πιστοποιητικών στους συγγενείς θυμάτων. Στις 20 Μαρτίου 2026, η δικαστής Μ. Χαρίση ανακάλεσε γραπτή απόφασή της μέσα σε ώρες, καταγγελλόμενη ως «τρομοκρατημένη» από παρεμβάσεις. Ενδείξεις εκβιασμού, βίαιου ή μη, εσωτερικά της εξουσίας.',
    documentation_order: 'Β\'',
    references: [
      'https://www.iefimerida.gr/ellada/tempi-diekopi-diki-gia-binteoliptiko-lipothymise-i-proedros',
      'https://www.in.gr/2026/03/19/greece/tempi-nea-diakopi-logo-kolymatos-tisproedrou-sti-diki-gia-ta-vinteo/',
    ],
    score: 10,
    status: 'Ενεργό',
    section: 'thesmoi',
    subsection: 'Δικαστική Εξουσία',
  },
  {
    id: 'thesmoi-3',
    title: 'Θεσμική Σιωπή ΠτΔ',
    date: '2026',
    category: 'Ε\'',
    type: 'Θεσμική',
    description: 'Ο Πρόεδρος της Δημοκρατίας παραμένει σιωπηλός παρά τις καταγεγραμμένες πιέσεις και ενδεχόμενους εκβιασμούς σε δικαστές. Η αδράνεια του ΠτΔ συνιστά de facto θεσμική εγκατάλειψη.',
    documentation_order: 'Β\'',
    references: [],
    score: 8,
    status: 'Ενεργό',
    section: 'thesmoi',
    subsection: 'Εκτελεστική Εξουσία',
  },
  {
    id: 'thesmoi-4',
    title: 'Μπαράζ ΠΝΠ μετά τις Εκλογές',
    date: 'Ιούνιος–Ιούλιος 2023',
    category: 'Α\'',
    type: 'Θεσμική',
    description: 'Έκδοση ≥5 Πράξεων Νομοθετικού Περιεχομένου εντός ολίγων εβδομάδων (ΠΝΠ ΕΚΑΒ: ΦΕΚ Α\' 132/05.07.2023· ΠΝΠ πυρόπληκτων Αυγ. 2023) χωρίς επαρκή αιτιολόγηση έκτακτης ανάγκης.',
    documentation_order: 'Α\'',
    references: ['ΦΕΚ Α\' 132/05.07.2023'],
    score: 6,
    status: 'Έκλεισε',
    section: 'thesmoi',
    subsection: 'Νομοθετική Εξουσία',
  },
]
